channels:
- conda-forge
dependencies:
- python=3.8
- pip
- pip:
  - torchmetrics<0.7
  - cloudpickle
  - torch
  - transformers
  - pandas
  - azureml-sdk
  - ipadic
  - fugashi
  - unidic-lite
  - sentencepiece
  - protobuf
  - mlflow
name: distributed_pytorch_env